baseURL = "https://convoyfireandems.com"
languageCode = "en-us"
title = "Navigator | Responsive Multipurpose Bootstrap Hugo Template"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "G-J3537SM93V" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
#defaultContentLanguageInSubdir = false
#DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/convoy_logo_banner.png"

# meta data
author = "Convoy Fire and EMS"
description = "Convoy Fire and EMS official website"

# Gestion des langues : FR / EN / NL / DE
############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "Convoy Fire & EMS"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/convoy_logo_banner.png"
menufixed = true

footerDescription = "Your local Convoy Fire & EMS official webpage. We are here to help."
#footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
#footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = false
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Volunteer Fire Fighters and EMTs Wanted"
description = "Our community depends (or relies) on dedicated volunteers to help keep everyone safe. We are seeking motivated individuals to serve as Volunteer Firefighters and EMTs to support local emergency services. No prior experience is required. We provide all training to state standards, along with the necessary protective gear and equipment. Volunteers respond to fires, medical emergencies, accidents, and other critical situations while working as part of a committed team."
button  = true
btnText = "Want to know more?"
btnURL  = "faq/volunteer/"
#videoThumb = "images/team/2025/Staff.jpg"
videoThumb = "images/official_Logo.png"
#videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Have you checked your smoke detectors lately?"
description = "Test units monthly. Install new batteries immediately when the low-battery warning alarm sounds or at least once a year. Clean smoke alarms regularly by vacuuming them with a brush attachment. Replace smoke alarms every 10 years to achieve optimum performance."

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = false
topTitle= "OUR UNTOLD STORY"
title   = "Blog."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "DROP US A NOTE"
title   = "Contact Us."
subtitle= ""
address = "117 Franklin St<br> Convoy, OH 45832"
phone   = "911"
fax     = "419-749-2997"
facebook= "https://www.facebook.com/convoyfd"
#twitter = "https://twitter.com/"
#linkedin= "https://www.linkedin.com/"
#dribbble= "https://dribbble.com/"
#instagram= "https://www.instagram.com/"
mapLatitude = "40.91735"
mapLongitude= "-84.70655"
#mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = false
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Create Something Together"
subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

[params.upcomingEvent]
enabled = true
title = "Pancake Breakfast Fundraiser"
date = "Saturday, Feb 7th - 6 AM thru 1 PM"
location = "Edgewood Park Community Building"
url = "/events/pancake2026/"


#Site Menus
[menu]
#Navbar Menus
[[menu.nav]]
name    = "Events"
url     = "/events/"
weight  = 1

[[menu.nav]]
name    = "Volunteer"
url     = "faq/volunteer/"
weight  = 2

[[menu.nav]]
name    = "FAQ"
url     = "faq"
weight  = 3

#[[menu.nav]]
#name    = "Photos"
#url     = "photos"
#weight  = 4
#[[menu.nav]]
#name    = "blog"
#url     = "blog"
#weight  = 5


# Footer Service Menu
#[[menu.service]]
#name    = "graphicdesign"
#url     = "service"
#weight  = 1
#[[menu.service]]
#name    = "webdesign"
#url     = "service"
#weight  = 2
#[[menu.service]]
#name    = "webdevelopment"
#url     = "service"
#weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "village"
url     = "http://villageofconvoy.com"
weight  = 1
[[menu.quicklink]]
name    = "CERT"
url     = "https://www.facebook.com/vwcert"
weight  = 2
[[menu.quicklink]]
name    = "Email"
url     = "https://outlook.com/convoyfireandems.com"
weight  = 3 